binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5  #Change the pin num to what you used
      mode:
        input: true
    name: LD012 Ladar
    device_class: occupancy
    filters:
      - delayed_on: 100ms
      - delayed_off: 5s  #Delay Off Timer
  - platform: gpio
    pin:
      number: GPIO1  #Change the pin num to what you used
      mode:
        output: true
    name: LD012 Sen
